apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-dash-app
  description: a dash app
  tags:
    - website
  links:
    - url: https://fv-eta-processes-app-tst.azurewebsites.net/
      title: My Dashboard
      icon: dashboard
    - url: https://fv-eta-processes-app-tst.azurewebsites.net/
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/view-url: https://fv-eta-processes-app-tst.azurewebsites.net/
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: KyleHawk/Django_Web
spec:
  type: website
  lifecycle: production
  owner: guests
  system: examples
  providesApis:
      - example-api